### ISSUE TITLE
Add AcceptKeys assert

### ISSUE THREAD

**Issue by ricardogama** [seegno/validator.js-asserts#43]
I've been using this assert a lot, validating if an object has invalid keys, which seems handy:

```js
validate({ foo }, {
  foo: new Assert().AcceptKeys(['bar', 'biz'])
}
```

Producing results like these:

```js
{ bar: '', biz: '' } // Valid
{ bar: '' } // Valid
{} // Valid
{ bar: '', qux: '' } // Invalid
{ qux: '' } // Invalid
```

@nunofgs @ruimarinho What do you think, should I open a PR with this feature?

**Comment by ruimarinho** [comment]
SGTM. This is exactly like should.js [Assertion#properties(names)](http://shouldjs.github.io/#assertion-properties), while `EqualKeys` is similar to [Assertion#keys([keys])](http://shouldjs.github.io/#assertion-keys).

**Comment by ricardogama** [comment]
Cool, I'll open a PR then.
